/**
 * Created by liu on 16/7/17.
 */
var messages =[
    {
        type:'微信',
        time:'现在',
        txt:'老婆:这周我爸生日,下班早点回来给我爸买礼物去!'
    },{
        type:'QQ',
        time:'现在',
        txt:'客户王总:你现在马上来'
    },{
        type:'短信',
        time:'现在',
        txt:'客户王总:你现在马上来'
    },{
        type:'QQ',
        time:'现在',
        txt:'客户王总:这周我爸生日.阿斯顿撒'
    },{
        type:'支付宝',
        time:'现在',
        txt:'阿斯顿:你现在马上来'
    },{
        type:'QQ',
        time:'现在',
        txt:'客户王总:这周我爸生日'
    },{
        type:'微信',
        time:'现在',
        txt:'儿童:你现在马上来'
    },{
        type:'微信',
        time:'现在',
        txt:'啊啊:这周我爸生日'
    },{
        type:'QQ',
        time:'现在',
        txt:'客户王总:你现在马上来'
    },{
        type:'支付宝',
        time:'现在',
        txt:'客户王总:你现在马上来'
    },{
        type:'短信',
        time:'现在',
        txt:'客户王总:你现在马上来'
    },{
        type:'微信',
        time:'现在',
        txt:'客户王总:你现在马上来'
    },{
        type:'支付宝',
        time:'现在',
        txt:'客户王总:你现在马上来'
    },{
        type:'微信',
        time:'现在',
        txt:'客户王总:你现在马上来'
    }
]